# "Synthesize Medical Data"

> First attempt
- toc: true
- branch: master
- badges: false
- comments: true
- hide: false
- search_exclude: true
- metadata_key1: metadata_value1
- metadata_key2: metadata_value2
- image: images/SurvivalAnalysis_lifelines.png
- categories: [Medical_Industry,  Medical_Data_Synthesis]
- show_tags: true

This is a first attempt to synthesize the data. The product of this notebook represents the "true" data. This data should then be 

* contaminated with noise, e.g. dropping/inserting a character here and there, using variants of names, etc 
* split into different source datasets, for example, one for *patients*, one for *encounters*, one for *conditions*, and one for *medications*.

Once this is done, the different datasets can be subjected to a data science pipeline to combine again and perform machine learning.

In [1]:
import pandas as pd
pd.__version__

'1.4.2'

In [2]:
from random import sample

## 1 DATA SOURCES

In [3]:
LAST_NAMES = [ #for starters - need proper list
    'Abrahams', 'Bladwin', 'Smith', 'Johnson', 'Williams', 'Brown', 
    'Jones', 'Garcia', 'Miller', 'Davis', 'Marinez', 'Lopez', 'Gonzalez', 
    'Wilson', 'Anderson', 'Thomas', 'Taylor', 'Moore', 'Jackson', 
    'Martin', 'Lee', 'Perez', 'Thompson', 'White', 'Harris', 'Clark']

In [4]:
FIRST_NAMES = [ #for starters - need proper list
    'James', 'Robert', 'Mary', 'Patricia', 'John', 'Jennifer',
    'Michael', 'Linda', 'William', 'Elizabeth', 'David', 'Barbara',
    'Richard', 'Susan', 'Joseph', 'Jessica', 'Thomas', 'Sarah',
    'Charles', 'Karen', 'Christopher', 'Nancy', 'Daniel', 'Lisa']

In [5]:
STREET_NAMES = [ #for starters - need proper list
'Main Street', 'Church Street', 'Main Street North', 'Main Street South', 'Elm Street'
'High Street','Main Street West','Washington Street','Main Street East',
'Park Avenue','2nd Street','Walnut Street','Chestnut Street','Maple Avenue',
'Maple Street','Broad Street','Oak Street','Center Street','Pine Street',
'River Road','Market Street','Water Street','Union Street','South Street',
'Park Street','3rd Street','Washington Avenue','Cherry Street','North Street',
'4th Street','Court Street','Highland Avenue','Mill Street','Franklin Street',
'Prospect Street','School Street','Spring Street','Central Avenue','1st Street',
'State Street','Front Street','West Street','Jefferson Street','Cedar Street']

In [6]:
CITIES = [ #for starters - need proper list
'Alexander City','Andalusia','Anniston','Athens','Atmore','Auburn','Bessemer',
'Birmingham','Chickasaw','Clanton','Ketchikan','Kodiak','Kotzebue','Nome',
'Palmer','Seward','Sitka','Harrison','Helena','Hope','Hot Springs','Jacksonville',
'Jonesboro','Little Rock','Magnolia','Morrilton','Newport','Claremont',
'Compton','Concord','Corona','Coronado','Costa Mesa','Culver City',
'Daly City','Davis','Irvine','La Habra','Laguna Beach','Lancaster',
'Livermore','Lodi','Lompoc','Long Beach','Los Angeles','Malibu','Martinez',
'Marysville','Menlo Park','Merced','Modesto','Monterey','Mountain View',
'Napa','Needles','Newport Beach','Norwalk','Novato','Oakland','Oceanside',
'Ojai','Alexander City','Andalusia','Anniston','Athens','Atmore','Auburn',
'Bessemer','Birmingham','Chickasaw','Clanton','Ketchikan','Kodiak',
'Kotzebue','Nome','Palmer','Seward','Sitka','Harrison','Helena','Hope',
'Hot Springs','Jacksonville','Jonesboro','Little Rock','Magnolia','Morrilton',
'Newport','Claremont','Compton','Concord','Corona','Coronado','Costa Mesa',
'Culver City','Daly City','Davis','Irvine','La Habra','Laguna Beach',
'Lancaster','Livermore','Lodi','Lompoc','Long Beach','Los Angeles',
'Malibu','Martinez','Marysville','Menlo Park','Merced','Modesto','Monterey',
'Mountain View','Napa','Needles','Newport Beach','Norwalk','Novato',
'Oakland','Oceanside','Ojai'
]

In [7]:
df_con_med = pd.read_csv('condition_medication.csv')
df_con_med

       api_num                     disease                          drug
0            0   Alkylating Agent Cystitis            sodium bicarbonate
1            1   Alkylating Agent Cystitis  citric acid / sodium citrate
2            2        Abdominal Distension                   bethanechol
3            3        Abdominal Distension                      pamabrom
4            4        Abdominal Distension                   bethanechol
...        ...                         ...                           ...
14678    14677  Zollinger-Ellison Syndrome                  lansoprazole
14679    14678  Zollinger-Ellison Syndrome                    ranitidine
14680    14679  Zollinger-Ellison Syndrome                   rabeprazole
14681    14680  Zollinger-Ellison Syndrome                    cimetidine
14682    14681  Zollinger-Ellison Syndrome                  esomeprazole

[14683 rows x 3 columns]

In [8]:
# hide
# https://data.world/datasets/names

In [9]:
# hide
con_med_sample = df_con_med.sample()
con_med_sample

      api_num          disease        drug
5639    14634  Facial Wrinkles  tazarotene

In [10]:
# hide
con_med_sample['disease'].values[0]

'Facial Wrinkles'

In [11]:
# hide
con_med_sample['drug'].values[0]

'tazarotene'

In [14]:
# hide
sample(LAST_NAMES, 1)

['Abrahams']

## 2 SYNTHESIZE DATA

In [18]:
df = pd.DataFrame(columns=[
    'pat_last', 'pat_first', 'pat_street', 'pat_city', 'pat_zip', 'pat_state', 'pat_dob', #'pat_gender', #PATIENT
    'enc_date', 'enc_practitioner_last', 'enc_practitioner_first', 'enc_practitioner_role', 'enc_type', #ENCOUNTER
    'con_name', 'con_diag_date', #CONDITION
    'med_name' #MEDICATION
])
dp = []
for i in range(10000):
    #PATIENT
    #hardcoded for now - need to sample from list
    dp = [sample(LAST_NAMES, 1)[0]]+[sample(FIRST_NAMES, 1)[0]]+[sample(STREET_NAMES, 1)[0]]+[sample(CITIES, 1)[0]]+['98230']+['WA']+['2007-01-01'] #['M']+ #PATIENT
    #ENCOUNTER
    #hardcoded for now - need to sample from list
    dp = dp + ['2021-07-22']+[sample(LAST_NAMES, 1)[0]]+[sample(FIRST_NAMES, 1)[0]]+['Physician/RN/PA/etc']+['FirstVisit/Checkup/Refil/etc'] #ENCOUNTER    
    #CONDITION
    con_med_sample = df_con_med.sample()
    dp = dp + [con_med_sample['disease'].values[0]]+['2001-12-04'] #CONDITION
    #MEDICATION    
    dp = dp + [con_med_sample['drug'].values[0]] #MEDICATION
    #add new datapoint to dataframe
    df.loc[i] = dp

In [19]:
df

,pat_last,pat_first,pat_street,pat_city,pat_zip,pat_state,pat_dob,enc_date,enc_practitioner_last,enc_practitioner_first,enc_practitioner_role,enc_type,con_name,con_diag_date,med_name
0,Marinez,Linda,Prospect Street,Mountain View,98230,WA,2007-01-01,2021-07-22,Smith,Sarah,Physician/RN/PA/etc,FirstVisit/Checkup/Refil/etc,Temporal Arteritis,2001-12-04,triamcinolone
1,Williams,Karen,State Street,Claremont,98230,WA,2007-01-01,2021-07-22,Gonzalez,Robert,Physician/RN/PA/etc,FirstVisit/Checkup/Refil/etc,Yellow Fever Prophylaxis,2001-12-04,yellow fever vaccine
2,Brown,Sarah,State Street,Ketchikan,98230,WA,2007-01-01,2021-07-22,Miller,Patricia,Physician/RN/PA/etc,FirstVisit/Checkup/Refil/etc,Breast Cancer,2001-12-04,capecitabine
3,Gonzalez,James,State Street,Oakland,98230,WA,2007-01-01,2021-07-22,Moore,Jessica,Physician/RN/PA/etc,FirstVisit/Checkup/Refil/etc,Acne,2001-12-04,benzoyl peroxide
4,Abrahams,Sarah,State Street,Morrilton,98230,WA,2007-01-01,2021-07-22,Williams,Thomas,Physician/RN/PA/etc,FirstVisit/Checkup/Refil/etc,CMV Prophylaxis,2001-12-04,letermovir
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,Davis,John,Spring Street,Lancaster,98230,WA,2007-01-01,2021-07-22,Brown,Daniel,Physician/RN/PA/etc,FirstVisit/Checkup/Refil/etc,Niemann-Pick Disease,2001-12-04,miglustat
9996,Moore,Robert,Mill Street,Lompoc,98230,WA,2007-01-01,2021-07-22,Perez,Nancy,Physician/RN/PA/etc,FirstVisit/Checkup/Refil/etc,Lichen Planus,2001-12-04,clobetasol
9997,Smith,Jessica,Union Street,Novato,98230,WA,2007-01-01,2021-07-22,Taylor,James,Physician/RN/PA/etc,FirstVisit/Checkup/Refil/etc,Osteoarthritis,2001-12-04,celecoxib
9998,Garcia,Joseph,Highland Avenue,Claremont,98230,WA,2007-01-01,2021-07-22,Garcia,Charles,Physician/RN/PA/etc,FirstVisit/Checkup/Refil/etc,Herpes Zoster,2001-12-04,valacyclovir
9999,Miller,Linda,2nd Street,Anniston,98230,WA,2007-01-01,2021-07-22,Clark,Jessica,Physician/RN/PA/etc,FirstVisit/Checkup/Refil/etc,Prostatitis,2001-12-04,doxycycline